stages:
  - name: Build
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: louvre-ticketsystem:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yml