version: '3.7'
services:
  db:
    image: postgres:9.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: louvre
      POSTGRES_USER: louvre
      POSTGRES_PASSWORD: louvre
    networks:
      - database

  app:
    build: .
    volumes:
      - ${PWD}:/var/www/louvre:cached
    ports:
      - 9000:9000
    networks:
      - database
      - default

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ${PWD}:/var/www/louvre:cached
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    networks:
      - default

networks:
  database:
    internal: true
